### ISSUE TITLE
Rendering on hand held devices

### ISSUE THREAD

**Issue by Fnyasimi** [bioinformatics-hub-ke/BOSS22#47] opened 2022-03-14 16:39 UTC
The top navigation bar is slightly off

**Comment by bkmgit** [comment] 2022-03-15 13:53
Can you add more detail on what should be changed?

**Comment by bkmgit** [comment] 2022-03-15 19:06
Previewed the site at https://ready.mobi/ - https://github.com/bioinformatics-hub-ke/BOSS22/pull/48 possibly will resolve this as it removes "BOSS 2022" from the header.

**Comment by bkmgit** [comment] 2022-03-15 19:22
Other related tools:
- https://mobilemoxie.com/tools/mobile-page-test/
- https://www.responsinator.com
- https://search.google.com/test/mobile-friendly
- https://www.bing.com/webmaster/tools/mobile-friendliness

**Comment by Fnyasimi** [comment] 2022-03-15 20:17
Checked it out on those platforms and the top navigation bars are still tucked behind each other i.e you cannot access the registration tab

**Comment by bkmgit** [comment] 2022-04-03 07:11
Ok hamburger menu feature described at https://mmistakes.github.io/minimal-mistakes/docs/navigation/#masthead seems not to be working.

**Comment by bkmgit** [comment] 2022-04-03 08:18
Related links
- https://github.com/mmistakes/minimal-mistakes/pull/2674
- https://github.com/mmistakes/minimal-mistakes/issues/1301

**Comment by bkmgit** [comment] 2022-04-05 08:14
@Fnyasimi Thanks for reporting this. Closing due to https://github.com/bioinformatics-hub-ke/BOSS22/pull/63. Feel free to reopen if you find the issue is not resolved.

**Closed by bkmgit** 2022-04-05 08:14 UTC
